### ISSUE TITLE
iterativeMotorMixing explanation

### ISSUE THREAD

**Issue by tiralonghipol** [sigma-pi/L1AC_ardupilot#1]
hi @sigma-pi  !
thank you so much for open-sourcing this! 
Is there any reference/math for the iterativeMotorMixing function in mode_adaptive.cpp?

**Comment by Sheng-Cheng** [comment]
Hi @tiralonghipol ,

Thanks for reaching out to us! The function iterativeMotorMixing simply runs Newton's method to solve for rotor speed from commanded thrust and moment. We perform one step of Newton's method each time calling the function. 

Best,
Sheng

**Comment by sigma-pi** [comment]
Hi @tiralonghipol, we also have a simplified motor mixing method assuming that the thrust to torque coefficient is a constant (check equation (1) of the geometric control paper https://ieeexplore.ieee.org/document/5717652). We use the following function to convert the thrust-moment command to individual thrusts for each motor, and then use the thrust to PWM curve to get the proper motor PWM signal.
`
VectorN<float,4> ModeAdaptive::TM2F(VectorN<float,4> TM)
{
    // convert from thrust moment to individual thrust
    // L = 0.175;
    // D = 0.131;
    // k = 0.0176956175; % M/f
    // TM[0] = f1+f2+f3+f4;
    // TM[1] = -L/2*f1+L/2*f2+L/2*f3-L/2*f4;
    // TM[2] = D/2*f1-D/2*f2+D/2*f3-D/2*f4;
    // TM[3] = k*f1+k*f2-k*f3-k*f4;

    VectorN<float, 4> indf;
    float f = TM[0];
    float M1 = TM[1];
    float M2 = TM[2];
    float M3 = TM[3];

    indf[0] = 0.25*f+(-2.8571)*M1+(3.8168)*M2+(14.1278)*M3;
    indf[1] = 0.25*f+(2.8571)*M1+(-3.8168)*M2+(14.1278)*M3;
    indf[2] = 0.25*f+(2.8571)*M1+(3.8168)*M2+(-14.1278)*M3;
    indf[3] = 0.25*f+(-2.8571)*M1+(-3.8168)*M2+(-14.1278)*M3;
      
    return indf; 
}
`

**Comment by tiralonghipol** [comment]
That make sense, thank you for your fast reply.
And what are the units of u_ad_prev, the variable returned at the end of L1AdaptiveAugmentation?
